// ============================================================================
// /api/verify-payment.js — SERVER-SIDE AUTHORITY (HARDENED)
//
// Two paths:
//   A) Founder: paymentMode === 'founder' + founderToken (server-generated nonce)
//   B) Razorpay: standard signature verification
//
// Security: Founder path requires a one-time token generated by create-order
// to prevent frontend-only bypass. Token is consumed on use.
//
// Single-price model: every new session gets replyEnabled = true. Legacy
// sessions retain their original replyEnabled value (no back-migration).
// ============================================================================

import crypto from 'crypto';
import admin from 'firebase-admin';
import { adminDb, guardPost, rateLimit } from './lib/middleware.js';
import { getSessionUser } from './lib/auth.js';
import { validateCoupleData as parseCoupleData } from '../lib/coupleDataValidator.js';
import { extractRequestId } from './lib/requestId.js';
import { sendLetterSealedEmail } from '../lib/email/sendEmail.js';

const MIN_PRICE_PAISE = 24900;  // ₹249 — single price floor

// PR #18a: atomic-with-success draft completion. Called from BOTH the founder
// branch and the Razorpay branch AFTER the existing payment-success multi-path
// write resolves. Internal try/catch swallows errors — payment success must
// NOT regress on a draft-write failure. No-op if the user was guest at
// payment time, or never explicitly saved a draft, or has no ACTIVE draft.
async function markActiveDraftCompleted(senderUid) {
  if (!senderUid) return;
  try {
    const draftsSnap = await adminDb
      .ref(`users/${senderUid}/drafts`)
      .orderByChild('persistenceStatus')
      .equalTo('ACTIVE')
      .once('value');
    const drafts = draftsSnap.val() || {};
    const draftKeys = Object.keys(drafts);
    // PR #18b CP5 — defense-in-depth observability. The single-ACTIVE
    // invariant is enforced at write time in api/drafts/save.js; if more
    // than one ACTIVE draft is ever discovered here, it points at corruption
    // (manual DB edit, pre-invariant data, race that bypassed save.js).
    // Behavior is unchanged: chronologically oldest ACTIVE wins
    // (Object.keys preserves RTDB push-key insertion order, which is
    // chronological). The warn-log surfaces the anomaly for triage.
    if (draftKeys.length > 1) {
      console.warn(
        `[verify-payment] Multiple ACTIVE drafts found for uid=${senderUid}; operating on chronologically oldest. count=${draftKeys.length}`,
      );
    }
    const activeDraftId = draftKeys[0]; // single-ACTIVE invariant ⇒ ≤1 normally
    if (!activeDraftId) return;
    await adminDb
      .ref(`users/${senderUid}/drafts/${activeDraftId}`)
      .update({
        draftState: 'COMPLETED',
        updatedAt: admin.database.ServerValue.TIMESTAMP,
      });
    // persistenceStatus stays ACTIVE — COMPLETED is a draftState, not a status.
    // 18d may add a sweep that transitions COMPLETED drafts to a final status.
  } catch (err) {
    console.error('[verify-payment] draft completion write failed:', err.message);
  }
}

/**
 * PR-46 — Send the "Your letter has been sealed" email to the sender.
 *
 * Mirrors markActiveDraftCompleted's discipline:
 *   - Non-critical-path side effect
 *   - Never throws; never bubbles
 *   - Logs success/failure/skip-reason with requestId for correlation
 *   - Caller awaits but never gates HTTP response on result
 *
 * Skip conditions (each logged):
 *   - No authenticated sender (guest payment) → no email source
 *   - amount <= 0 (founder path) → no receipt to send
 *   - Already-sent guard via notifications/{paymentId}/letterSealedSentAt
 *
 * Idempotency note: best-effort single-check-then-set. Concurrent duplicate
 * invocations could theoretically result in two emails (small race window
 * between read and post-send write). Acceptable for V1; full transactional
 * idempotency is deferrable to PR-46.X if duplicate-email events are observed.
 */
async function sendLetterSealedNotification({ sessionUser, sanitized, paymentId, amountPaise, requestId }) {
  // Guard 1: guest sender — no email available
  if (!sessionUser || !sessionUser.email) {
    console.log('[Verify] Email skipped — no authenticated sender email', {
      requestId,
      paymentId,
      senderUid: sessionUser?.uid || null,
    });
    return;
  }

  // Guard 2: founder path — amount == 0, no receipt to send
  if (!amountPaise || amountPaise <= 0) {
    console.log('[Verify] Email skipped — non-paid path (founder access)', {
      requestId,
      paymentId,
      senderUid: sessionUser.uid,
    });
    return;
  }

  // Guard 3: idempotency — already sent for this paymentId
  // Stored at notifications/{paymentId}/letterSealedSentAt — separate from
  // payments/{paymentId} because the existing multi-path write overwrites
  // that object on retry, which would wipe a flag stored there.
  try {
    const sentSnapshot = await adminDb.ref(`notifications/${paymentId}/letterSealedSentAt`).once('value');
    if (sentSnapshot.exists()) {
      console.log('[Verify] Email skipped — already sent for this payment (idempotency)', {
        requestId,
        paymentId,
        previouslyAt: sentSnapshot.val(),
      });
      return;
    }
  } catch (idempotencyReadErr) {
    // RTDB read failure: skip send conservatively to avoid possible duplicate.
    console.error('[Verify] Email idempotency check failed — skipping send', {
      requestId,
      paymentId,
      error: idempotencyReadErr.message,
    });
    return;
  }

  // Format inputs for the locked template
  const formattedAmount = `₹${(amountPaise / 100).toFixed(2)}`;
  const formattedDate = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'Asia/Kolkata',
  });
  // formattedDate example: "11 May 2026" (en-GB locale, IST)

  // Send
  let sendResult;
  try {
    sendResult = await sendLetterSealedEmail({
      to: sessionUser.email,
      senderName: sanitized.senderName || 'there',
      formattedAmount,
      paymentId,
      formattedDate,
    });
  } catch (sendErr) {
    // sendLetterSealedEmail is documented never-throws; belt-and-suspenders.
    console.error('[Verify] Email send threw (unexpected)', {
      requestId,
      paymentId,
      error: sendErr.message,
    });
    return;
  }

  if (!sendResult || sendResult.ok !== true) {
    console.error('[Verify] Email send failed', {
      requestId,
      paymentId,
      error: sendResult?.error || 'unknown',
    });
    return;
  }

  console.log('[Verify] Email sent', {
    requestId,
    paymentId,
    resendMessageId: sendResult.id,
  });

  // Mark sent for idempotency
  try {
    await adminDb.ref(`notifications/${paymentId}/letterSealedSentAt`).set(new Date().toISOString());
  } catch (markErr) {
    // Worst case: a retry could re-send. Log loudly. Don't fail the response.
    console.error('[Verify] Email idempotency-mark write failed (possible duplicate on retry)', {
      requestId,
      paymentId,
      resendMessageId: sendResult.id,
      error: markErr.message,
    });
  }
}

function generateShortId() {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  const bytes = crypto.randomBytes(8);
  let result = '';
  for (let i = 0; i < 8; i++) {
    result += chars[bytes[i] % chars.length];
  }
  return result;
}

function slugify(text) {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 30);
}

// C11+C12 fix: route through the shared Zod schema in lib/coupleDataValidator.js.
// The schema validates EVERY field including nested objects (sacredLocation,
// memoryBoard[], video, audio, coupons[]) and enforces the URL allowlist on
// every URL-typed field. The previous hand-rolled version only sanitized
// top-level strings — nested objects passed through unmodified, allowing
// `javascript:` URIs to land in shared/{sessionKey}.sacredLocation.googleMapsUri
// and similar nested paths.
//
// Returns null on validation failure (preserves the existing call-site contract
// at lines 156 and 419: `if (!sanitized) return res.status(400)`).
function validateCoupleData(data) {
  if (!data || typeof data !== 'object') return null;

  // Total payload size cap before schema parse (cheap denial-of-service guard).
  try {
    if (JSON.stringify(data).length > 200_000) return null;
  } catch {
    return null;
  }

  const result = parseCoupleData(data);
  if (!result.success) {
    console.warn('[Verify] coupleData validation failed:', result.error);
    return null;
  }
  return result.data;
}


// ══════════════════════════════════════════════════════════════════════
// MAIN HANDLER
// ══════════════════════════════════════════════════════════════════════

export default async function handler(req, res) {
  if (guardPost(req, res)) return;

  // M4: mutation route — never cache responses.
  res.setHeader('Cache-Control', 'no-store');

  // H1: correlation ID — set by create-order, forwarded by client. Used in
  // every log line and stored on shared/{sessionKey} + payments/{paymentId}
  // so an operator can grep one ID for the entire payment journey.
  const requestId = extractRequestId(req);

  // ── GLOBAL IP RATE LIMITING ──
  const { limited } = await rateLimit(req, {
    keyPrefix: 'payment_rate',
    windowSeconds: 60,
    max: 5,
  });

  if (limited) {
    return res.status(429).json({
      error: "Too many requests. Please wait a minute."
    });
  }

  // Resolve sender identity (optional — guests are still supported).
  // When present, we mirror the letter to users/{uid}/letters/{sessionKey}
  // so it shows up in the sender's dashboard.
  const senderSessionUser = await getSessionUser(req);
  const senderUid = senderSessionUser?.uid || null;

  const {
    razorpay_order_id,
    razorpay_payment_id,
    razorpay_signature,
    coupleData,
    paymentMode,
    founderToken,
  } = req.body || {};

  // ════════════════════════════════════════════════════════════
  // PATH A: FOUNDER ACCESS
  // ════════════════════════════════════════════════════════════
  if (paymentMode === 'founder') {
    if (!founderToken || typeof founderToken !== 'string') {
      return res.status(400).json({ verified: false, error: 'Invalid request.' });
    }
    if (!coupleData || typeof coupleData !== 'object') {
      return res.status(400).json({ verified: false, error: 'Missing session data.' });
    }

    // claimMarker tracks the exact timestamp we wrote during the transaction.
    // The rollback block (catch) uses it to verify ownership: if another
    // request consumed the token between our failure and our rollback attempt,
    // claimMarker mismatch prevents us from un-consuming someone else's claim.
    let claimMarker = 0;
    try {
      const tokenRef = adminDb.ref('founderTokens/' + founderToken);
      const claimResult = await tokenRef.transaction(current => {
        // Serverless (Vercel) has no local cache — first call may receive null.
        // Returning null triggers Firebase to retry with real server data.
        // Returning undefined (bare return) would ABORT the transaction.
        if (current === null) return null;
        if (current.consumed) return;
        if (!current.createdAt || Date.now() - current.createdAt > 5 * 60 * 1000) return;

        claimMarker = Date.now();
        return {
          ...current,
          consumed: true,
          consumedAt: claimMarker,
        };
      });

      const tokenData = claimResult.snapshot.val();
      if (!claimResult.committed || !tokenData || !tokenData.consumed) {
        return res.status(400).json({ verified: false, error: 'Invalid request.' });
      }

      const sanitized = validateCoupleData(coupleData);
      if (!sanitized) {
        return res.status(400).json({ verified: false, error: 'Invalid session data.' });
      }

      // Every new session has reply enabled under the single-price model.
      const replyEnabled = true;

      // Generate session key
      let sessionKey = '';
      for (let attempt = 0; attempt < 5; attempt++) {
        sessionKey = generateShortId();
        try {
          const existsSnap = await adminDb.ref('shared/' + sessionKey).once('value');
          const exists = existsSnap.val();
          if (!exists) break;
        } catch { break; }
        if (attempt === 4) {
          return res.status(500).json({ verified: false, error: 'Session creation failed. Please retry.' });
        }
      }

      const now = new Date().toISOString();
      const founderId = `founder_${Date.now()}`;

      const updates = {};
      updates[`shared/${sessionKey}`] = {
        ...sanitized,
        replyEnabled,
        status: 'paid',
        sealedAt: now,
        createdAt: sanitized.createdAt || now,
        paymentId: founderId,
        paymentMode: 'founder',
        paidAmount: 0,
        ...(senderUid ? { senderUid } : {}),
        ...(requestId ? { requestId } : {}),
      };

      updates[`payments/${founderId}`] = {
        paymentId: founderId,
        paymentMode: 'founder',
        amount: 0,
        replyEnabled,
        sessionKey,
        verifiedAt: now,
        ...(requestId ? { requestId } : {}),
      };

      if (senderUid) {
        updates[`users/${senderUid}/letters/${sessionKey}`] = {
          sessionKey,
          createdAt: Date.now(),
        };
      }

      await adminDb.ref().update(updates);
      await tokenRef.remove().catch(() => {});

      // PR #18a — atomic-with-success: mark the user's ACTIVE draft COMPLETED.
      // No-op for guests; helper internally swallows errors.
      await markActiveDraftCompleted(senderUid);

      // PR-46 — letter-sealed notification email. Founder path always skips
      // (amount=0 → Guard 2). Call retained for code symmetry + future
      // founder-email policy without re-touching this block.
      await sendLetterSealedNotification({
        sessionUser: senderSessionUser,
        sanitized,
        paymentId: founderId,
        amountPaise: 0,
        requestId,
      });

      const senderSlug = slugify(sanitized.senderName || 'sender');
      const receiverSlug = slugify(sanitized.recipientName || 'receiver');
      const shareSlug = `${senderSlug}--${receiverSlug}--${sessionKey}`;

      console.log('[Verify] ✓ FOUNDER', { requestId, sessionKey, paymentId: founderId });

      return res.status(200).json({
        verified: true,
        sessionKey,
        shareSlug,
        replyEnabled,
        paymentId: founderId,
      });
    } catch (error) {
      // Best effort rollback
      try {
        const tokenRef = adminDb.ref('founderTokens/' + founderToken);
        await tokenRef.transaction(current => {
          if (!current || !current.consumed) return current;
          if (current.consumedAt && current.consumedAt !== claimMarker) return current;
          return {
            ...current,
            consumed: false,
            consumedAt: null,
          };
        });
      } catch {}

      console.error('[Verify] Founder error', { requestId, error: error.message });
      return res.status(500).json({ verified: false, error: 'Session creation failed.' });
    }
  }

  // ════════════════════════════════════════════════════════════
  // PATH B: NORMAL RAZORPAY FLOW
  // ════════════════════════════════════════════════════════════
  if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
    return res.status(400).json({ verified: false, error: 'Missing payment fields.' });
  }
  if (!coupleData || typeof coupleData !== 'object') {
    return res.status(400).json({ verified: false, error: 'Missing session data.' });
  }

  const keySecret = process.env.RAZORPAY_KEY_SECRET;

  if (!keySecret) {
    console.error('[Verify] Missing RAZORPAY_KEY_SECRET', { requestId });
    return res.status(500).json({ verified: false, error: 'Server configuration error.' });
  }

  try {
    // 1. VERIFY RAZORPAY SIGNATURE
    const body = razorpay_order_id + '|' + razorpay_payment_id;
    const expected = crypto.createHmac('sha256', keySecret).update(body).digest('hex');

    let isValid;
    try {
      isValid = crypto.timingSafeEqual(
        Buffer.from(expected, 'hex'),
        Buffer.from(razorpay_signature, 'hex'),
      );
    } catch {
      isValid = false;
    }

    if (!isValid) {
      console.warn('[Verify] Signature mismatch', { requestId, orderId: razorpay_order_id });
      return res.status(400).json({ verified: false, error: 'Payment verification failed.' });
    }

    // 2. ATOMIC CLAIM ON payments/{paymentId}
    // Prevents duplicate sessions on retry/double-submit. Mirrors the
    // founder-token pattern at lines 128-149.
    let claimMarker = 0;
    let existingRecord = null;

    const paymentRef = adminDb.ref('payments/' + razorpay_payment_id);

    try {
      const claimResult = await paymentRef.transaction(current => {
        if (current !== null) {
          // Already claimed — capture for replay return path below
          existingRecord = current;
          return; // abort transaction, don't overwrite
        }
        claimMarker = Date.now();
        return {
          claiming: true,
          claimedAt: claimMarker,
          orderId: razorpay_order_id,
          paymentId: razorpay_payment_id,
        };
      });

      if (!claimResult.committed) {
        // Replay or race detected. Try to return existing sessionKey.
        let final = existingRecord;

        // If existing record has no sessionKey yet, the original
        // request is mid-flight. Wait and re-read up to 3 seconds.
        if (!final || !final.sessionKey) {
          for (let attempt = 0; attempt < 6; attempt++) {
            await new Promise(r => setTimeout(r, 500));
            const retrySnap = await paymentRef.once('value');
            const retryVal = retrySnap.val();
            if (retryVal && retryVal.sessionKey) {
              final = retryVal;
              break;
            }
          }
        }

        // Final attempt before giving up
        if (!final || !final.sessionKey) {
          const finalSnap = await paymentRef.once('value');
          const finalVal = finalSnap.val();
          if (finalVal && finalVal.sessionKey) {
            final = finalVal;
          }
        }

        if (final && final.sessionKey) {
          const s = slugify(coupleData.senderName || 'sender');
          const r = slugify(coupleData.recipientName || 'receiver');
          return res.status(200).json({
            verified: true,
            replay: true,
            sessionKey: final.sessionKey,
            shareSlug: `${s}--${r}--${final.sessionKey}`,
            replyEnabled: final.replyEnabled || false,
            paymentId: razorpay_payment_id,
          });
        }

        // IMPORTANT — DO NOT "FIX" THIS TO RETURN 500 OR 409:
        // We intentionally return 200 even when sessionKey is not ready,
        // because the client (PaymentStage.tsx) treats any non-200 as
        // a payment failure and triggers a new Razorpay order on retry
        // → double charge risk.
        //
        // The `processing: true` flag is a forward-compatible signal:
        // current client code falls into its existing reject path
        // (verified is false), but future client code can hook into
        // `processing` to show a proper "still processing" UI state.
        //
        // The C1 reconciliation system (next PR) will catch any orphan
        // payments that fall through this branch.
        console.error('[Verify] Race unresolved after retries', { requestId, paymentId: razorpay_payment_id });
        return res.status(200).json({
          verified: false,
          processing: true,
          error: 'Payment is processing. Please wait a moment and refresh.',
        });
      }
    } catch (claimError) {
      // Genuine error in the claim transaction itself (RTDB outage, etc.)
      // This is NOT a post-payment success state — the original request
      // may not have reached us. Returning 500 here is acceptable
      // because no payment record was successfully created.
      console.error('[Verify] Claim transaction failed', { requestId, paymentId: razorpay_payment_id, error: claimError.message });
      return res.status(500).json({
        verified: false,
        error: 'Payment verification failed. Please contact support.',
      });
    }

    // Claim succeeded — proceed with session provisioning below.

    // 3. RESOLVE AMOUNT FROM SERVER-SIDE ORDER RECORD
    //    NEVER trust client-provided amounts. The order record in Firebase
    //    (written by create-order.js) is the single source of truth.
    let orderAmount;

    try {
      const orderSnap = await adminDb.ref('orders/' + razorpay_order_id).once('value');
      const orderData = orderSnap.val();

      if (!orderData || !orderData.amount) {
        console.error('[Verify] Order record missing or incomplete', { requestId, orderId: razorpay_order_id });
        return res.status(500).json({
          verified: false,
          error: 'Unable to verify order. Please contact support.',
        });
      }

      if (orderData.amount < MIN_PRICE_PAISE) {
        console.error('[Verify] Order amount below minimum', { requestId, orderId: razorpay_order_id, amount: orderData.amount });
        return res.status(500).json({
          verified: false,
          error: 'Unable to verify order. Please contact support.',
        });
      }

      orderAmount = orderData.amount;
    } catch (orderErr) {
      console.error('[Verify] Order lookup failed', { requestId, orderId: razorpay_order_id, error: orderErr.message });
      return res.status(500).json({
        verified: false,
        error: 'Payment verification temporarily unavailable. Please retry.',
      });
    }

    // Every new session has reply enabled under the single-price model.
    const replyEnabled = true;

    // 4. VALIDATE COUPLE DATA
    const sanitized = validateCoupleData(coupleData);
    if (!sanitized) {
      return res.status(400).json({ verified: false, error: 'Invalid session data.' });
    }

    // 5. GENERATE SESSION KEY
    let sessionKey = '';
    for (let attempt = 0; attempt < 5; attempt++) {
      sessionKey = generateShortId();
      try {
        const existsSnap = await adminDb.ref('shared/' + sessionKey).once('value');
        const exists = existsSnap.val();
        if (!exists) break;
      } catch {
        break;
      }
      if (attempt === 4) {
        return res.status(500).json({ verified: false, error: 'Session creation failed. Please retry.' });
      }
    }

    // 6. ATOMIC MULTI-PATH WRITE
    const now = new Date().toISOString();

    const updates = {};

    updates[`shared/${sessionKey}`] = {
      ...sanitized,
      replyEnabled,
      status: 'paid',
      sealedAt: now,
      createdAt: sanitized.createdAt || now,
      paymentId: razorpay_payment_id,
      orderId: razorpay_order_id,
      ...(senderUid ? { senderUid } : {}),
      ...(requestId ? { requestId } : {}),
    };

    updates[`payments/${razorpay_payment_id}`] = {
      orderId: razorpay_order_id,
      paymentId: razorpay_payment_id,
      amount: orderAmount,
      replyEnabled,
      sessionKey,
      verifiedAt: now,
      ...(requestId ? { requestId } : {}),
    };

    updates[`orders/${razorpay_order_id}/status`] = 'paid';

    if (senderUid) {
      updates[`users/${senderUid}/letters/${sessionKey}`] = {
        sessionKey,
        createdAt: Date.now(),
      };
    }

    try {
      await adminDb.ref().update(updates);
    } catch (writeError) {
      // Multi-path update failed AFTER we successfully claimed the
      // payment. Roll back the claim placeholder so a manual retry
      // can proceed cleanly. Verify claimMarker still matches ours
      // (don't roll back another request's later claim — same
      // discipline as the founder rollback at lines 226-243).
      console.error('[Verify] Multi-path update failed, rolling back claim', { requestId, paymentId: razorpay_payment_id, error: writeError.message });
      try {
        await paymentRef.transaction(current => {
          if (!current || !current.claiming) return current;
          if (current.claimedAt !== claimMarker) return current;
          return null; // delete the placeholder
        });
      } catch (rollbackError) {
        console.error('[Verify] CRITICAL: rollback also failed', { requestId, paymentId: razorpay_payment_id, error: rollbackError.message });
        // Manual reconciliation will be needed for this paymentId.
        // C1 reconciliation system (next PR) will detect this orphan.
      }
      throw writeError; // bubble up to outer catch at line 491
    }

    // PR #18a — atomic-with-success: mark the user's ACTIVE draft COMPLETED.
    // No-op for guests; helper internally swallows errors. Placed AFTER the
    // multi-path write succeeds so it never fires on payment failure.
    await markActiveDraftCompleted(senderUid);

    // PR-46 — letter-sealed notification email. Authenticated paying senders
    // only (guests + founder path skip via internal guards). Non-critical
    // path: helper never throws and never gates this HTTP response.
    await sendLetterSealedNotification({
      sessionUser: senderSessionUser,
      sanitized,
      paymentId: razorpay_payment_id,
      amountPaise: orderAmount,
      requestId,
    });

    // 7. RETURN SHARE URL
    const senderSlug = slugify(sanitized.senderName || 'sender');
    const receiverSlug = slugify(sanitized.recipientName || 'receiver');
    const shareSlug = `${senderSlug}--${receiverSlug}--${sessionKey}`;

    console.log('[Verify] ✓', { requestId, sessionKey, paymentId: razorpay_payment_id });

    return res.status(200).json({
      verified: true,
      sessionKey,
      shareSlug,
      replyEnabled,
      paymentId: razorpay_payment_id,
    });

  } catch (error) {
    console.error('[Verify] Error', { requestId, error: error.message });
    return res.status(500).json({ verified: false, error: 'Verification system error.' });
  }
}
